### ISSUE TITLE
Impressão por valor - Necessita finalizar o jeito correto do codigo

### ISSUE THREAD

**Issue by EduardoCamargoMarin** [EduardoCamargoMarin/Aplica-o_JS#3]
Jeito correto deve ter essa configuração no console.
E
ED
EDU
EDUA
EDUAR
EDUARD
EDAURDO

**Comment by RoPupo** [comment]
Utilizando C#, pode se utilizar dois metodos diferentes 
Tente utilizar o FOR, mas atribuindo os valores a seus vetores de for "E" "ED" "EDU" ... assim por diante conforme exemplo



Console.WriteLine("Metodo For :");

string[] sobrenome = { "P", "PU", "PUP", "PUPO" };
for (int i = 0; i < sobrenome.Length; ++i)
{
    Console.WriteLine(sobrenome[i]);
}
 // Mesmo resultado, utilizando menos comandos
Console.WriteLine("");
Console.WriteLine( "Metodo Foreach :");

string[] rodrigo = { "R", "RO", "ROD", "RODR", "RODRI", "RODRIG", "RODRIGO" };
foreach (string nome in rodrigo)
{
    Console.WriteLine(nome);
}
